#!/usr/bin/python
import os
from json import dumps
from os.path import join
from sys import argv


def get_all_files(folder, filter_function)-> list:
    files = []
    try:
        files = os.listdir(folder)
    except:
        return []
    files_and_content = []
    for file in files:
        current = os.path.join(folder, file)
        if os.path.isdir(current):
            sub_content = get_all_files(current, filter_function)
            files_and_content += sub_content
        elif filter_function(current):
                files_and_content.append(current)
    return files_and_content

def main():
    if len(argv) < 2:
        print("please specify a folder to scan")
        return

    folder = argv[1]
    instances = get_all_files(os.path.join(folder, "params"), filter_function= lambda x: ".param" in x)
    number_of_instances = len(instances)
    f = open(join(folder, "ProblemData.json"), "w")
    f.write(dumps({"NumberOfInstances":number_of_instances}))
    f.close()
main()
