#!/usr/bin/python
from sys import argv
import os
from json import load

def get_all_files(folder, filter_function)-> list:
    files = []
    try:
        files = os.listdir(folder)
    except:
        return []
    files_and_content = []
    for file in files:
        current = os.path.join(folder, file)
        if os.path.isdir(current):
            sub_content = get_all_files(current, filter_function)
            files_and_content += sub_content
        elif filter_function(current):
                files_and_content.append(current)
    return files_and_content

def main():
    files = get_all_files(argv[1], lambda x: "ProblemData.json" in x)
    data = []
    for file in files:
        with open(file) as f:
            data.append(load(f))
    data = sorted(data, key=lambda x: x["NumberOfInstances"], reverse=True)
    for i in range(len(data)):
        print(f"{i}) {data[i]['model']} with {data[i]['NumberOfInstances']} instances")

main()
